services:
  app:
    image: registry.digitalocean.com/message-board/message-board:0.0.1
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    platform: linux/x86_64
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
